In [6]:
import numpy as np
import pandas as pd
import matplotlib as plt

In [3]:
a = [1,2,3,4]
b = [2,3,4,5]

In [4]:
a

[1, 2, 3, 4]

In [5]:
b

[2, 3, 4, 5]

In [11]:
a = np.array([1.14,2,3,4.1])
b = np.array([2,3,4,5])

In [12]:
a

array([1.14, 2.  , 3.  , 4.1 ])

In [15]:
a.ndim

1

In [16]:
a.shape

(4,)

In [18]:
np.random.randint(10, size = (3,3,2))

array([[[9, 7],
        [7, 6],
        [7, 9]],

       [[3, 9],
        [0, 8],
        [7, 1]],

       [[9, 1],
        [5, 7],
        [3, 2]]])

In [20]:
c = np.arange(0,10)

In [21]:
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
x = 5*np.array([1,2,3])
y = np.array([3,4,5])

In [23]:
np.concatenate([x,y])

array([1, 2, 3, 3, 4, 5])

In [25]:
x

array([ 5, 10, 15])

In [26]:
5*np.array([1,2,3])

array([ 5, 10, 15])

In [27]:
d = np.array([4,6,5,1,3,2])

In [28]:
np.sort(d)

array([1, 2, 3, 4, 5, 6])

In [29]:
a[0]

1.14

In [30]:
d[-1]

2

In [31]:
d[-1] = 22

In [32]:
d

array([ 4,  6,  5,  1,  3, 22])

In [35]:
m = np.random.randint(10,size = (3,5))

In [36]:
m

array([[5, 3, 8, 2, 9],
       [8, 8, 2, 1, 6],
       [7, 0, 3, 8, 3]])

In [37]:
m[2,1]

0

In [38]:
m[1,4]

6

In [39]:
m[1,4] = 6.6

In [40]:
m

array([[5, 3, 8, 2, 9],
       [8, 8, 2, 1, 6],
       [7, 0, 3, 8, 3]])

In [41]:
m[0:3]

array([[5, 3, 8, 2, 9],
       [8, 8, 2, 1, 6],
       [7, 0, 3, 8, 3]])

In [43]:
n = np.random.randint(10,size=(5,5))

In [44]:
n

array([[1, 2, 5, 1, 6],
       [0, 0, 8, 6, 0],
       [2, 0, 2, 7, 2],
       [8, 1, 5, 4, 1],
       [7, 4, 1, 6, 0]])

In [45]:
n[:,0]

array([1, 0, 2, 8, 7])

In [46]:
m[1,:]

array([8, 8, 2, 1, 6])

In [47]:
n[1,:]

array([0, 0, 8, 6, 0])

In [56]:
n[1,2:4]

array([8, 6])

In [60]:
n[1:3,2:4]

array([[8, 6],
       [2, 7]])

In [61]:
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
alt_a = a[0:3, 0:2]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [64]:
v = np.arange(0,30,2)
v

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [65]:
v[1]

2

In [66]:
v[5]

10

In [67]:
al_getir = [1,3,5]

In [68]:
v[al_getir]

array([ 2,  6, 10])

In [71]:
m = np.arange(9).reshape((3,3))

In [72]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [88]:
m[:,2]

array([2, 5, 8])

In [73]:
satır = np.array([0,1])

In [74]:
satır

array([0, 1])

In [76]:
sutun = np.array([1,2])

In [77]:
m[satır,sutun]

array([1, 5])

In [78]:
v > 5

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [79]:
np

<module 'numpy' from 'C:\\Users\\testinium\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>

In [80]:
?np

Type:        module
String form: <module 'numpy' from 'C:\\Users\\testinium\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\testinium\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x 

In [82]:
a = np.array([[5,1],[1,3]])

In [83]:
b = np.array([12,10])

In [84]:
x = np.linalg.solve(a,b)

In [85]:
x

array([1.85714286, 2.71428571])

In [ ]:
#Tek seri

In [2]:
sozluk = {"reg":10,"carl":11,"corc":13}

In [3]:
sozluk

{'reg': 10, 'carl': 11, 'corc': 13}

In [7]:
seri = pd.Series(sozluk)

In [8]:
seri

reg     10
carl    11
corc    13
dtype: int64

In [9]:
#İki Seriyi birleştirme

In [11]:
pd.concat([seri,seri])

reg     10
carl    11
corc    13
reg     10
carl    11
corc    13
dtype: int64